Adding Android robot teleoperation demo.
eclipse-zenoh/zenoh-demos pull request #14
Opened 2023-11-10 16:05 UTC by gabrik

- [x] Make the app work
- [ ] Remove all the old examples
- [ ] Improve configuration

2024-01-02 16:43 UTC, gabrik commented
@DariusIMP can you have a look and see if it is Android enough?

2024-01-29 10:56 UTC, DariusIMP requested changes
I added a couple of comments. The app code could probably be improved but I understand our focus is to show how to use Zenoh in such a use case so I don't want to be too nit picky.

In general, besides the comments, I'd recommend to remove all the unnecessary commented code, which adds noise to the example, and to format the project [see how](https://www.jetbrains.com/help/idea/reformat-and-rearrange-code.html#reformat_module_directory).

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/java/com/example/zenohapp/ros/Battery.kt
> +        //Log.v("BatteryConstructor", "streamPos: ${inputStream.buffer.position()} - ${this.toString()}")
Can we remove these commented logs? or uncomment them?

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/java/com/example/zenohapp/ros/Header.kt
> +        //Log.v("Header","streamPos: ${inputStream.buffer.position()} - ${this.toString()}")
Same here

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/java/com/example/zenohapp/ros/Image.kt
> +//            val b = data[3*i].toInt()
Can we remove these?

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/java/com/example/zenohapp/ui/examples/TeleopFragment.kt
> +    override fun onTouch(v: View?, event: MotionEvent?): Boolean {
So whenever you touch the fragment layout, this callback is going to be triggered and it's going to check if the touch happened on a button?
I'd instead set for each button an implementation for [Button::onTouchEvent(MotionEvent event)](https://developer.android.com/reference/android/widget/TextView#onTouchEvent(android.view.MotionEvent)).

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/java/com/example/zenohapp/ui/examples/TeleopFragment.kt
> +            R.id.buttonDeclare -> {
Here it'd be more efficient to do something like

```kotlin
mDeclareButton.setOnClickListener(v -> {
    declarePublisher()
    startPubSub()
})
```
and same thing for the other buttons

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/zenohapp_menu.jpeg
I guess you are not going to use these images, I'd suggest we remove them from here. I also suggest that you add an image of the teleop fragment into the README, in order to let users know what they are going to find out when installing this app.

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/res/layout/fragment_example.xml
It seems to me you are not using this, we could remove it.

2024-01-29 10:56 UTC, DariusIMP commented on zenoh-android/RobotTeleop/app/src/main/res/layout/fragment_gallery.xml
This seems to me can be removed, as well as the fragment_home.xml, fragment_slideshow.xml. I probably missed this on my original example.

2024-07-15 15:30 UTC, merged