Zenoh-pico add ROS2 Unix example using CycloneDDS CDR serializer
eclipse-zenoh/zenoh-demos pull request #8
Opened 2023-02-09 14:03 UTC by PetervdPerk-NXP

Adds a UNIX example to communicate with ROS2 using the native ROS2 message definitions.

For serialization we use the CycloneDDS CDR serializer, for now we compile some components separately. But ideally we would have to have do decouple some modules from CycloneDDS i.e. dds_cdrstream.c and turn it into a standalone library that could run also on small RTOS'es (FreeRTOS, Zephyr and more)

To use the UNIX example you've to specify the ROS_DISTRO and it will automatically generated the definitions and serializer to communicate on a ROS2 topic. For more information see https://github.com/NXPHoverGames/zenoh-demos/blob/400df907eaf50416b36fc729e9bd5a0d0c44f428/ROS2/zenoh-pico-cyclonedds-cdr-message-log/README.md

Furthermore this PR has a soft dependency to this https://github.com/eclipse-cyclonedds/cyclonedds/pull/1564 PR to avoiding that we compile the complete DDS stack.

2023-02-13 10:13 UTC, gabrik commented
Thank you for your contribution.
Before merging this PR we need to wait for https://github.com/eclipse-cyclonedds/cyclonedds/pull/1564  to be merged.

2023-02-16 10:09 UTC, cguimaraes requested changes
LGTM.
Just pending a merge on last tweaks:
  - Removed unused variables
  - Apply formatting guidelines.

IMO, it can be merged even before the CycloneDDS PR is accepted. The only impact is building the entire CycloneDDS suite when we just require the IDL part.

2023-02-16 10:09 UTC, cguimaraes commented on ROS2/zenoh-pico-cyclonedds-cdr-message-log/z_pub_ros2.c
> +    const char *value = "Pub from Pico IDL!";
This variable is not used.
I did a PR to remove unused variable and apply formatting.

2023-02-20 09:19 UTC, Mallets commented
> LGTM. Just pending a merge on last tweaks:
> 
> * Removed unused variables
> * Apply formatting guidelines.
> 
> IMO, it can be merged even before the CycloneDDS PR is accepted. The only impact is building the entire CycloneDDS suite when we just require the IDL part.

I believe we can go on with accepting the PR and to clearly state in the README that you'd need to build the entire CycloneDDS suite until the corresponding PR is accepted.

2023-02-20 10:27 UTC, cguimaraes approved these changes

2023-02-20 10:29 UTC, merged